import {
  AnimatePresence,
  motion,
  useMotionValue,
  useTransform,
} from 'framer-motion';
import Head from 'next/head';
import Link from 'next/link';
import { useState } from 'react';

export default function Home() {
  return (
    <div className='container'>
      <Head>
        <title>Exit Animations</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='main'>
        <h1 className='title'>Exit Animations</h1>
        <p className='description'>
          Using <code>{'<AnimatePresence>'}</code> to animate components when
          they exit the DOM. <Link href='/'>Go back</Link>
        </p>

        {(() => {
          const img = {
            src: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
          };
          const [isVisible, setIsVisible] = useState(true);
          return (
            <AnimatePresence>
              <h2>Simple Click to Exit</h2>;
              {isVisible && (
                <motion.img
                  key={img.src}
                  src={img.src}
                  initial={{ opacity: 0, y: 200 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  onClick={() => setIsVisible(!isVisible)}
                />
              )}
            </AnimatePresence>
          );
        })()}

        {(() => {
          const imgs = [
            'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8a3lvdG98ZW58MHx8MHx8&auto=format&fit=crop&w=400&q=60',
            'https://images.unsplash.com/photo-1578469645742-46cae010e5d4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8a3lvdG98ZW58MHx8MHx8&auto=format&fit=crop&w=400&q=60',
            'https://images.unsplash.com/photo-1558862107-d49ef2a04d72?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8a3lvdG98ZW58MHx8MHx8&auto=format&fit=crop&w=400&q=60',
          ];
          const [index, setIndex] = useState(0);
          return (
            <>
              <AnimatePresence>
                <h2>Slideshow</h2>
                <div>
                  <button onClick={() => setIndex(Math.max(0, index - 1))}>
                    Previous
                  </button>
                  <button
                    onClick={() =>
                      setIndex(Math.min(index + 1, imgs.length - 1))
                    }
                  >
                    Next
                  </button>
                </div>
                <motion.img
                  key={index}
                  src={imgs[index]}
                  initial={{ opacity: 0, x: 1000, zIndex: 0 }}
                  animate={{ opacity: 1, x: 0, zIndex: 1 }}
                  exit={{ opacity: 0, x: -1000, zIndex: 0 }}
                />
              </AnimatePresence>
            </>
          );
        })()}
      </main>
    </div>
  );
}
