import type { NextPage } from 'next';
import Head from 'next/head';

import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className='title'>Ready-to-Use Framer Motion Components</h1>
        <p className='description'>
          Using this as a learning playground for Framer Motion. Will eventually
          publish these components in a UI library.
        </p>
      </main>
    </div>
  );
};

export default Home;
